name = "akhlus"
author = "akhlus"
variant = "dark"
opacity_ghostty = "0.95"
opacity_zed = ""
base00 = "#101010"       # base
base01 = "#161616"       # mantle
base02 = "#323232"       # surface0
base03 = "#454545"       # surface1
base04 = "#5c5c5c"       # surface2
base05 = "#e7e7e7"       # text
base06 = "#f5108c"       # rosewater ##
base07 = "#b4be1e"       # lavender ##
base08 = "#ff5964"       # red
base09 = "#f89777"       # peach
base0A = "#f8d353"       # yellow
base0B = "#06d6a0"       # green
base0C = "#72e9c5"       # teal ##
base0D = "#5eb0fc"       # blue
base0E = "#9e72e9"       # purple
base0F = "#a6e3a1"       # lime
